### ISSUE TITLE
predict_scClassify error: long vectors not supported yet

### ISSUE THREAD

**Issue by 0x644BE25** [SydneyBioX/scClassify#1]
I'm trying run predict_scClassify() on a sparse matrix (dgCMatrix) with 26561 features and 50562 cells, and get this error:

`Error in `[<-`(x, i, value = value) : 
  long vectors not supported yet: memory.c:3486
Calls: predict_scClassify ... predict_scClassifySingle -> calculateSimilarity -> [<- -> [<- -> [<- -> [<-
Execution halted
`

**Comment by YingxinLin** [comment]
Hi,

Thank you for your interest in scClassify. I am wondering what similarity you have chosen to run scClassify. 

Cheers,
Yingxin

**Comment by 0x644BE25** [comment]
I was using the default settings, so it should have been using "pearson" similarity.

**Comment by YingxinLin** [comment]
Hi,

Thanks for letting us know the issue. I have a quick fixed for the package regarding Pearson similarity. Please install the latest version of scClassify and let us know if it works.

Cheers,
Yingxin

**Comment by YingxinLin** [comment]
Hi Carolyn,

Thank you so much for providing the script! I have reproduced the error, and I found that it is because in as number of cells both training and testing dataset is 50562, scClassify tries to calculate a  50562* 50562 sparse correlation matrix, greater than the limit of 2^31 elements that R could handle for sparse matrix. 

I am currently addressing this issues for sparse matrix (The script can be run via dense matrix, but it is very memory consuming).  I will also suggest to use a subsample of the data to train the model. In the meantime, I will also implement a function to subsample the data to handle such case.

Thank you again for the script. And I will update you about the package development asap.

Best wishes,
Yingxin

**Comment by worsteggs** [comment]
> Hi Carolyn,
> 
> Thank you so much for providing the script! I have reproduced the error, and I found that it is because in as number of cells both training and testing dataset is 50562, scClassify tries to calculate a 50562* 50562 sparse correlation matrix, greater than the limit of 2^31 elements that R could handle for sparse matrix.
> 
> I am currently addressing this issues for sparse matrix (The script can be run via dense matrix, but it is very memory consuming). I will also suggest to use a subsample of the data to train the model. In the meantime, I will also implement a function to subsample the data to handle such case.
> 
> Thank you again for the script. And I will update you about the package development asap.
> 
> Best wishes, Yingxin

Hi Yingxin, I meet the same error. Do you know if this issue has been solved or not?
My scClassify version is 1.6.0.

Best wishes,
Zilch
